options:
  merge-default-rules: true
files:
  include: 'src/scss/**/*.s[a,c]ss'
  ignore:
    - 'node_modules/'
rules:
  border-zero:
    - 2
    - convention: none
  brace-style:
      - 2
      - allow-single-line: false
  class-name-format:
    - 2
    - convention: hyphenatedbem
  clean-import-paths:
    - 2
    - leading-underscore: false
  declarations-before-nesting: 2
  empty-line-between-blocks: 2
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 2
    - include: true
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format: 0
  hex-length:
    - 2
    - style: long
  hex-notation:
    - 2
    - style: uppercase
  indentation:
    - 2
    - size: 2
  leading-zero:
    - 2
    - include: false
  mixins-before-declarations: 0
  nesting-depth:
    - 0
    - max-depth: 6
  no-css-comments: 0
  no-color-keywords: 2
  no-color-literals: 2
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties:
    - 2
    - extra-properties:
      - animate
      - overflow-scrolling
  no-scss-comments: 0
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-universal-selectors: 2
  no-vendor-prefixes: 2
  one-declaration-per-line: 2
  placeholder-in-extend: 0
  placeholder-name-format:
    - 2
    - convention: hyphenatedbem
  property-sort-order:
    - 2
    - order: smacss
  pseudo-element: 2
  quotes:
    - 2
    - style: single
  shorthand-values: 2
  single-line-per-selector: 2
  space-after-colon: 2
  space-around-operator: 2
  space-before-brace: 2
  trailing-semicolon: 2
  url-quotes: 2
  variable-name-format:
    - 2
    - convention: hyphenatedlowercase
  zero-unit: 2